### ISSUE TITLE
Empty state presented in table from SearchController presented over navigation bar is misplaced

### ISSUE THREAD

**Issue by hokster7** [DevonBoyer/DBEmptyState#2]
When the search controller is presented directly over a navigation bar, like in [this sample in UICatalog](https://developer.apple.com/library/ios/samplecode/UICatalog/Introduction/Intro.html), when I set a simple label to be the empty view, it's just in the wrong location.

![simulator screen shot 8 oct 2015 22 45 55](https://cloud.githubusercontent.com/assets/430233/10380869/7bc56b18-6e0e-11e5-86bd-6366dcbc8e59.png)

**Comment by devonboyer** [comment]
Are you sure the frame of the label is wrong? Sometimes when this happens to me it's because I forgot to set the labels **text alignment to centered**. The empty view will take up the entire frame of the table view taking into account content insets, if the empty view is set to a UILabel the frame itself will not be centered.

**Comment by hokster7** [comment]
Ah!

That makes sense. I sort of imagined that the view would center the relatively small label for me.
Thanks for the reply. @DevonBoyer

**Comment by devonboyer** [comment]
You can also subclass UIView and add any subviews with any constraints, and then set that custom view as the empty view. This is another approach I typically use.
